# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-09-25 13:01
from __future__ import unicode_literals

import FC15.models
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='BlogPost',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=150)),
                ('username', models.CharField(max_length=100)),
                ('content', models.TextField()),
                ('timestamp', models.DateTimeField()),
            ],
        ),
        migrations.CreateModel(
            name='FileInfo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('filename', models.CharField(max_length=255)),
                ('username', models.CharField(max_length=100)),
                ('teamname', models.CharField(max_length=100)),
                ('description', models.CharField(max_length=1000)),
                ('path', models.CharField(default='./fileupload/', max_length=500)),
                ('file', models.FileField(upload_to=FC15.models.FileInfo.user_dirpath)),
                ('timestamp', models.DateTimeField()),
            ],
        ),
        migrations.CreateModel(
            name='TeamInfo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('teamname', models.CharField(max_length=100)),
                ('captain', models.CharField(max_length=100)),
                ('introduction', models.CharField(max_length=500)),
            ],
        ),
        migrations.CreateModel(
            name='UserInfo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(max_length=100)),
                ('password', models.CharField(max_length=100)),
                ('stu_number', models.CharField(max_length=20)),
                ('email', models.EmailField(max_length=254)),
                ('team', models.CharField(max_length=100)),
            ],
        ),
    ]
