# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-09-26 02:03
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('FC15', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userinfo',
            name='team',
            field=models.CharField(default='', max_length=100),
        ),
    ]
