# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-09-26 03:27
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('FC15', '0002_auto_20170926_1003'),
    ]

    operations = [
        migrations.AlterField(
            model_name='fileinfo',
            name='path',
            field=models.CharField(max_length=500),
        ),
    ]
