# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-09-26 03:42
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('FC15', '0003_auto_20170926_1127'),
    ]

    operations = [
        migrations.AddField(
            model_name='fileinfo',
            name='origin_name',
            field=models.CharField(default=models.CharField(max_length=255), max_length=255),
        ),
    ]
