# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-09-30 04:04
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('FC15', '0004_fileinfo_origin_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='userinfo',
            name='activated',
            field=models.BooleanField(default=False),
        ),
    ]
