# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-09-30 04:09
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('FC15', '0005_userinfo_activated'),
    ]

    operations = [
        migrations.CreateModel(
            name='EmailActivate',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(max_length=100)),
                ('activate_string', models.CharField(max_length=100)),
            ],
        ),
    ]
