# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-09-30 10:10
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('FC15', '0006_emailactivate'),
    ]

    operations = [
        migrations.CreateModel(
            name='PasswordReset',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(max_length=100)),
                ('reset_string', models.CharField(max_length=100)),
                ('new_password', models.CharField(max_length=10)),
            ],
        ),
    ]
