# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-10-01 02:00
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('FC15', '0008_auto_20170930_2330'),
    ]

    operations = [
        migrations.AddField(
            model_name='teaminfo',
            name='members',
            field=models.IntegerField(default=0),
        ),
    ]
