# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-10-06 07:42
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('FC15', '0009_teaminfo_members'),
    ]

    operations = [
        migrations.AddField(
            model_name='fileinfo',
            name='compile_result',
            field=models.CharField(default='', max_length=4096),
        ),
        migrations.AddField(
            model_name='fileinfo',
            name='is_compile_success',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='fileinfo',
            name='is_compiled',
            field=models.BooleanField(default=False),
        ),
    ]
