# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-10-06 08:35
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('FC15', '0011_fileinfo_exact_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='fileinfo',
            name='is_compile_success',
            field=models.CharField(default='', max_length=50),
        ),
        migrations.AlterField(
            model_name='fileinfo',
            name='is_compiled',
            field=models.CharField(default='未编译', max_length=50),
        ),
    ]
