# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2018-01-25 03:17
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('FC15', '0012_auto_20171006_1635'),
    ]

    operations = [
        migrations.AlterField(
            model_name='fileinfo',
            name='is_compiled',
            field=models.CharField(default='Not compiled', max_length=50),
        ),
        migrations.AlterField(
            model_name='userinfo',
            name='team',
            field=models.CharField(default='', max_length=100, null=True),
        ),
    ]
