# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2018-02-09 03:34
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('FC15', '0013_auto_20180125_1117'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='blogpost',
            options={'ordering': ['timestamp'], 'verbose_name': 'blogpost'},
        ),
    ]
