# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2018-02-09 03:35
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('FC15', '0014_auto_20180209_1134'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='blogpost',
            options={'ordering': ['-timestamp'], 'verbose_name': 'blogpost'},
        ),
    ]
