# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2018-03-03 08:03
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('FC15', '0016_aiinfo'),
    ]

    operations = [
        migrations.CreateModel(
            name='GameRecord',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(max_length=100)),
                ('timestamp', models.DateTimeField()),
                ('filename', models.CharField(max_length=255)),
                ('state', models.CharField(max_length=50)),
            ],
        ),
    ]
