# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2018-03-11 16:21
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('FC15', '0017_gamerecord'),
    ]

    operations = [
        migrations.AlterField(
            model_name='aiinfo',
            name='description',
            field=models.CharField(blank=True, max_length=1000, null=True),
        ),
        migrations.AlterField(
            model_name='fileinfo',
            name='description',
            field=models.CharField(blank=True, max_length=1000, null=True),
        ),
        migrations.AlterField(
            model_name='fileinfo',
            name='teamname',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='userinfo',
            name='team',
            field=models.CharField(blank=True, default='', max_length=100, null=True),
        ),
    ]
