# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2018-03-13 01:29
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('FC15', '0018_auto_20180312_0021'),
    ]

    operations = [
        migrations.AlterField(
            model_name='fileinfo',
            name='description',
            field=models.CharField(blank=True, default='', max_length=1000, null=True),
        ),
        migrations.AlterField(
            model_name='fileinfo',
            name='teamname',
            field=models.CharField(blank=True, default='', max_length=100, null=True),
        ),
    ]
