# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2018-03-13 11:48
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('FC15', '0019_auto_20180313_0929'),
    ]

    operations = [
        migrations.AddField(
            model_name='gamerecord',
            name='AI1',
            field=models.CharField(blank=True, default='', max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='gamerecord',
            name='AI2',
            field=models.CharField(blank=True, default='', max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='gamerecord',
            name='AI3',
            field=models.CharField(blank=True, default='', max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='gamerecord',
            name='AI4',
            field=models.CharField(blank=True, default='', max_length=20, null=True),
        ),
    ]
