# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2018-03-17 13:41
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('FC15', '0020_auto_20180313_1948'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='gamerecord',
            options={'ordering': ['-timestamp'], 'verbose_name': 'username'},
        ),
        migrations.AddField(
            model_name='gamerecord',
            name='AI1_name',
            field=models.CharField(blank=True, default='', max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='gamerecord',
            name='AI2_name',
            field=models.CharField(blank=True, default='', max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='gamerecord',
            name='AI3_name',
            field=models.CharField(blank=True, default='', max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='gamerecord',
            name='AI4_name',
            field=models.CharField(blank=True, default='', max_length=20, null=True),
        ),
    ]
