# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2018-04-07 19:06
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('FC15', '0021_auto_20180317_1341'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='gamerecord',
            options={'ordering': ['-timestamp'], 'verbose_name': 'GameRecord'},
        ),
        migrations.AddField(
            model_name='userinfo',
            name='banned',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='fileinfo',
            name='is_compiled',
            field=models.CharField(default='', max_length=50),
        ),
    ]
