# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2018-04-07 23:37
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('FC15', '0024_auto_20180407_2109'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='teaminfo',
            name='rank',
        ),
        migrations.RemoveField(
            model_name='teaminfo',
            name='score',
        ),
        migrations.AddField(
            model_name='fileinfo',
            name='rank',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='fileinfo',
            name='score',
            field=models.IntegerField(default=0),
        ),
    ]
